channels:
- bioconda
- conda-forge
- defaults
- ome
dependencies:
- pip
- idr-py
- scikit-image=0.17.*
- scikit-learn=0.23.*
- bokeh=2.2.*
- ipywidgets
- matplotlib
- numpy
- pandas
- seaborn
- tifffile
